// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"swd-new/internal/handler"
	"swd-new/internal/repository"
	"swd-new/internal/server"
	"swd-new/internal/service"
	"swd-new/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	repositoryRepository := repository.NewRepository(logger, viperViper)
	sensitiveWordRepository, err := repository.NewSensitiveWordRepository(repositoryRepository)
	if err != nil {
		return nil, nil, err
	}
	sensitiveWordService, err := service.NewSensitiveWordService(serviceService, sensitiveWordRepository)
	if err != nil {
		return nil, nil, err
	}
	sensitiveWordHandler := handler.NewSensitiveWordHandler(handlerHandler, sensitiveWordService)
	engine := server.NewServerHTTP(logger, sensitiveWordHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewRepository, repository.NewSensitiveWordRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewSensitiveWordService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewSensitiveWordHandler)
